name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v5.6
      id: version
      with:
        release_branches: master,main
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Pack
      run: dotnet pack src/ExCSS/ExCSS.csproj -c Release --no-restore --version-suffix "${{ steps.version.outputs.new_version }}"
    
    - name: Publish 
      run: dotnet nuget push "src/ExCSS/bin/Release/ExCSS.*.nupkg" --skip-duplicate --source "https://nuget.pkg.github.com/VelocitySquared/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

